### ISSUE TITLE
support textual contracts

### ISSUE THREAD

**Issue by madnificent** [sellout/quid-pro-quo#12]
Some preconditions, postconditions and invariants are hard to specify in coded form yet still contain information about the contract.  It would be nice if there'd be some way to write a textual contract in there instead for reference to those that use or implement the class/method.

**Comment by sellout** [comment]
This currently only works for invariants. But invariants are also currently the only things that are included in the documentation, so …

**Comment by sellout** [comment]
Ok, `DOCUMENTATION` now works for generic functions and methods, so to get text-only pre- and postconditions, this should work:

``` common-lisp
(defrequirement foo (x) "X must be a function that always terminates" t)
```

**Comment by madnificent** [comment]
awesome!
