### ISSUE TITLE
Will not build on SBCL 1.1.17

### ISSUE THREAD

**Issue by scymtym** [sellout/quid-pro-quo#14]
Starting with (the not yet released) version 1.1.17, SBCL will no longer have `sb-int:arg-list`.

See http://cl-test-grid.appspot.com/blob?key=cc9ry6mb3y for the future error.

**Comment by quicklisp** [comment]
If not fixed, this will have an impact on the next Quicklisp release.

**Comment by sellout** [comment]
How long have I got, Doctor?

Hopefully I can get in a real fix, but at the very least I can make sure that I just disable contracts on non-generic functions in SBCL for the time being.

**Comment by quicklisp** [comment]
You have until sometime in april!

**Comment by sellout** [comment]
Pinging @orivej on this. He provided the sb-encapsulate code, and so he might understand better what’s changed. I took a quick swipe at it that didn’t work. If @orivej isn’t interested, I’ll spend more time on it.

**Comment by orivej** [comment]
I'll look into it today.
